-- No-op: unique index (tenant_id, email) already created by 20260220000002_patient_email_unique_per_tenant.
-- This migration was generated by Prisma after the fact; marking as applied without re-creating the index.
SELECT 1;
