/**
 * Questionário Anamnese Completa – baseado em docs/anamnese_completa.docx
 * Nutrição & Personal Training. Uso: template no seed.
 */
export const anamneseCompletaSchema = {
  questions: [
    // ─── 1. IDENTIFICAÇÃO PESSOAL ─────────────────────────────────────────
    { id: 'nome_completo', text: 'Nome completo:', type: 'text', required: true, tags: ['identificacao'] },
    { id: 'data_nascimento', text: 'Data de nascimento:', type: 'text', required: false, tags: ['identificacao'] },
    { id: 'idade', text: 'Idade:', type: 'number', required: false, tags: ['identificacao'] },
    { id: 'cpf_rg', text: 'CPF / RG:', type: 'text', required: false, tags: ['identificacao'] },
    { id: 'telefone', text: 'Telefone / WhatsApp:', type: 'text', required: true, tags: ['identificacao'] },
    { id: 'email', text: 'E-mail:', type: 'text', required: true, tags: ['identificacao'] },
    { id: 'endereco', text: 'Endereço completo:', type: 'text', required: false, tags: ['identificacao'] },
    { id: 'cidade_estado', text: 'Cidade / Estado:', type: 'text', required: false, tags: ['identificacao'] },
    { id: 'profissao', text: 'Profissão / Ocupação:', type: 'text', required: false, tags: ['identificacao'] },
    { id: 'estado_civil', text: 'Estado civil:', type: 'single', options: ['Solteiro(a)', 'Casado(a)', 'União estável', 'Divorciado(a)', 'Viúvo(a)', 'Outro'], required: false, tags: ['identificacao'] },
    { id: 'com_quem_mora', text: 'Com quem mora?', type: 'text', required: false, tags: ['identificacao'] },
    { id: 'numero_filhos', text: 'Número de filhos:', type: 'number', required: false, tags: ['identificacao'] },

    // ─── 2. DADOS ANTROPOMÉTRICOS ───────────────────────────────────────
    { id: 'peso_kg', text: 'Peso atual (kg):', type: 'number', required: true, tags: ['anthropometry'] },
    { id: 'altura_cm', text: 'Altura (cm):', type: 'number', required: true, tags: ['anthropometry'] },
    { id: 'imc', text: 'IMC calculado (ou deixe em branco para calcular):', type: 'number', required: false, tags: ['anthropometry'] },
    { id: 'circ_abdominal', text: 'Circunferência abdominal (cm):', type: 'number', required: false, tags: ['anthropometry'] },
    { id: 'circ_quadril', text: 'Circunferência do quadril (cm):', type: 'number', required: false, tags: ['anthropometry'] },
    { id: 'rcq', text: 'Relação cintura/quadril:', type: 'number', required: false, tags: ['anthropometry'] },
    { id: 'circ_pescoco', text: 'Circunferência do pescoço (cm):', type: 'number', required: false, tags: ['anthropometry'] },
    { id: 'circ_coxa', text: 'Circunferência da coxa (cm):', type: 'number', required: false, tags: ['anthropometry'] },
    { id: 'circ_braco', text: 'Circunferência do braço (cm):', type: 'number', required: false, tags: ['anthropometry'] },
    { id: 'pct_gordura', text: '% Gordura corporal (BF) estimado:', type: 'number', required: false, tags: ['anthropometry'] },
    { id: 'massa_muscular_kg', text: 'Massa muscular estimada (kg):', type: 'number', required: false, tags: ['anthropometry'] },

    // ─── 3. OBJETIVOS E MOTIVAÇÃO ────────────────────────────────────────
    {
      id: 'objetivo_principal',
      text: 'Objetivo principal (marque o principal):',
      type: 'single',
      options: [
        'Emagrecimento / Redução de gordura corporal',
        'Ganho de massa muscular (hipertrofia)',
        'Melhora do condicionamento físico / resistência',
        'Melhora da saúde e qualidade de vida',
        'Controle ou reversão de patologia (diabetes, hipertensão etc.)',
        'Melhora da performance esportiva',
        'Manutenção do peso e composição corporal atual',
        'Outro',
      ],
      required: true,
      tags: ['goal'],
    },
    { id: 'objetivo_outro', text: 'Se "Outro", descreva:', type: 'text', required: false, tags: ['goal'], showWhen: { questionId: 'objetivo_principal', operator: 'eq', value: 'Outro' } },
    { id: 'objetivo_descricao', text: 'Descreva com suas palavras o que você quer alcançar e em quanto tempo:', type: 'text', required: false, tags: ['goal'] },
    { id: 'motivacao', text: 'O que te motivou a buscar acompanhamento profissional agora?', type: 'text', required: false, tags: ['goal'] },
    { id: 'tentativas_anteriores', text: 'Você já tentou outras abordagens antes? Se sim, quais e com quais resultados:', type: 'text', required: false, tags: ['goal'] },

    // ─── 4. HISTÓRICO DE SAÚDE ───────────────────────────────────────────
    {
      id: 'doencas_diagnosticadas',
      text: 'Doenças diagnosticadas (marque todas que se aplicam):',
      type: 'multiple',
      options: [
        'Diabetes tipo 1',
        'Diabetes tipo 2',
        'Pré-diabetes / resistência insulínica',
        'Hipertensão arterial',
        'Dislipidemia (colesterol / triglicerídeos)',
        'Hipotireoidismo',
        'Hipertireoidismo',
        'Síndrome dos ovários policísticos (SOP)',
        'Síndrome metabólica',
        'Doenças cardiovasculares',
        'Doenças renais',
        'Doenças hepáticas (fígado)',
        'Doenças gastrointestinais (gastrite, colite, etc.)',
        'Câncer',
        'Osteoporose / osteopenia',
        'Anemia',
        'Ansiedade / depressão',
        'Transtorno alimentar',
        'HIV / imunossupressão',
        'Doenças autoimunes',
      ],
      required: false,
      tags: ['health'],
    },
    { id: 'doencas_outras', text: 'Outras doenças não listadas:', type: 'text', required: false, tags: ['health'] },
    { id: 'cirurgias', text: 'Histórico de cirurgias e internações (procedimento e ano):', type: 'text', required: false, tags: ['health'] },
    {
      id: 'historico_familiar',
      text: 'Parentes de 1º grau (pais, irmãos) com (marque todas que se aplicam):',
      type: 'multiple',
      options: ['Diabetes', 'Obesidade', 'Doenças cardiovasculares', 'Hipertensão', 'Câncer', 'Outras'],
      required: false,
      tags: ['health'],
    },

    // ─── 5. MEDICAMENTOS E SUPLEMENTOS ────────────────────────────────────
    { id: 'medicamentos_uso', text: 'Medicamentos de uso contínuo (nome, dose, há quanto tempo, motivo):', type: 'text', required: false, tags: ['medications'] },
    { id: 'suplementos_uso', text: 'Suplementos em uso (nome, dose, há quanto tempo, objetivo):', type: 'text', required: false, tags: ['medications'] },
    { id: 'exames_recentes', text: 'Exames laboratoriais recentes (transcreva valores e data se tiver):', type: 'text', required: false, tags: ['medications'] },

    // ─── 6. HÁBITOS ALIMENTARES ────────────────────────────────────────────
    { id: 'refeicoes_por_dia', text: 'Número de refeições por dia:', type: 'number', required: false, tags: ['diet'] },
    { id: 'horario_primeira_refeicao', text: 'Horário da primeira refeição:', type: 'text', required: false, tags: ['diet'] },
    { id: 'horario_ultima_refeicao', text: 'Horário da última refeição:', type: 'text', required: false, tags: ['diet'] },
    { id: 'refeicao_maior_volume', text: 'Refeição de maior volume / preferida:', type: 'text', required: false, tags: ['diet'] },
    { id: 'alimentos_gosta', text: 'Alimentos que GOSTA muito:', type: 'text', required: false, tags: ['diet'] },
    { id: 'alimentos_nao_gosta', text: 'Alimentos que NÃO GOSTA ou recusa comer:', type: 'text', required: false, tags: ['diet'] },
    { id: 'alergia_intolerancia', text: 'Alimentos que tem ALERGIA ou INTOLERÂNCIA comprovada:', type: 'text', required: false, tags: ['diet'] },
    {
      id: 'restricoes_alimentares',
      text: 'Restrições alimentares (marque todas que se aplicam):',
      type: 'multiple',
      options: ['Vegetariano', 'Vegano', 'Sem glúten', 'Sem lactose', 'Kosher / Halal', 'Sem açúcar (prescrição)', 'Restrição religiosa', 'Outra'],
      required: false,
      tags: ['diet'],
    },
    { id: 'agua_litros_dia', text: 'Água (litros/dia aproximado):', type: 'number', required: false, tags: ['diet'] },
    { id: 'sucos_frequencia', text: 'Consome sucos? Com que frequência?', type: 'text', required: false, tags: ['diet'] },
    { id: 'cafe_cha_dia', text: 'Café / chá (quantas xícaras/dia):', type: 'text', required: false, tags: ['diet'] },
    { id: 'refrigerante_energetico', text: 'Refrigerante / bebida energética:', type: 'text', required: false, tags: ['diet'] },
    { id: 'alcool', text: 'Consume bebidas alcoólicas? Se sim: tipo, frequência e quantidade:', type: 'text', required: false, tags: ['diet'] },
    { id: 'come_rapido', text: 'Come rápido, sem mastigar bem?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['diet'] },
    { id: 'come_tv_celular', text: 'Come assistindo TV, no celular ou trabalhando?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['diet'] },
    { id: 'compulsao_alimentar', text: 'Sente compulsão alimentar (comer sem fome, em grande quantidade)?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['diet', 'food_emotional'] },
    { id: 'come_ansiedade', text: 'Come por ansiedade, estresse ou emoções?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['diet', 'food_emotional'] },
    { id: 'pula_refeicoes', text: 'Pula refeições com frequência?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['diet'] },
    { id: 'beliscos', text: 'Faz beliscos entre as refeições?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['diet'] },
    { id: 'dia_tipico_alimentar', text: 'Descreva sua alimentação em um dia típico (café, almoço, jantar, lanches):', type: 'text', required: false, tags: ['diet'] },

    // ─── 7. ATIVIDADE FÍSICA ──────────────────────────────────────────────
    {
      id: 'nivel_atividade',
      text: 'Como você se classifica atualmente em relação à atividade física?',
      type: 'single',
      options: [
        'Sedentário (não pratica nenhuma atividade)',
        'Levemente ativo (caminhadas ocasionais, 1-2x/semana)',
        'Moderadamente ativo (exercícios 3-4x/semana)',
        'Muito ativo (treinos intensos 5-6x/semana)',
        'Atleta / extremamente ativo (treino diário ou duplo)',
      ],
      required: true,
      tags: ['activity'],
    },
    { id: 'modalidades_treino', text: 'Modalidades praticadas (modalidade, frequência x/semana, duração min, há quanto tempo):', type: 'text', required: false, tags: ['activity'] },
    { id: 'horario_treinos', text: 'Horário habitual dos treinos:', type: 'text', required: false, tags: ['activity'] },
    { id: 'local_treino', text: 'Local (academia, parque, casa):', type: 'text', required: false, tags: ['activity'] },
    { id: 'dor_limite_treino', text: 'Tem dor ou limitação física que afeta o treino? Se sim, descreva:', type: 'text', required: false, tags: ['activity'] },
    { id: 'lesao_previa', text: 'Já teve lesão musculoesquelética? Se sim, descreva (local, tipo, se foi tratada):', type: 'text', required: false, tags: ['activity'] },

    // ─── 8. SONO E RECUPERAÇÃO ───────────────────────────────────────────
    { id: 'horas_sono', text: 'Horas de sono por noite (média):', type: 'number', required: true, tags: ['sleep'] },
    { id: 'horario_dormir_acordar', text: 'Horário que dorme / acorda:', type: 'text', required: false, tags: ['sleep'] },
    { id: 'dificuldade_dormir', text: 'Tem dificuldade para dormir (insônia)?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['sleep'] },
    { id: 'acorda_noite', text: 'Acorda durante a noite?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['sleep'] },
    { id: 'acorda_descansado', text: 'Sente que acorda descansado?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['sleep'] },
    { id: 'medicamento_sono', text: 'Faz uso de medicamentos para dormir?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['sleep'] },
    { id: 'plantao_noturno', text: 'Faz plantões noturnos ou trabalha à noite?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['sleep'] },
    { id: 'observacoes_sono', text: 'Observações sobre o sono:', type: 'text', required: false, tags: ['sleep'] },

    // ─── 9. SAÚDE MENTAL E ESTRESSE ───────────────────────────────────────
    { id: 'nivel_estresse', text: 'Nível de estresse atual (0 = nenhum, 10 = máximo):', type: 'number', required: true, tags: ['stress'] },
    { id: 'estresse_intenso', text: 'Está passando por período de estresse intenso?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['stress'] },
    { id: 'ansiedade_depressao', text: 'Tem diagnóstico de ansiedade ou depressão?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['stress'] },
    { id: 'acompanhamento_psico', text: 'Faz acompanhamento psicológico / psiquiátrico?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['stress'] },
    { id: 'estresse_afeta_alimentacao', text: 'Como o estresse / emoções afetam sua alimentação e rotina?', type: 'text', required: false, tags: ['stress', 'food_emotional'] },

    // ─── 10. SAÚDE DIGESTIVA ─────────────────────────────────────────────
    { id: 'refluxo_gastrite', text: 'Tem refluxo / gastrite / úlcera?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['digestive'] },
    { id: 'sii', text: 'Tem síndrome do intestino irritável (SII)?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['digestive'] },
    { id: 'constipacao', text: 'Sofre de constipação (intestino preso)?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['digestive'] },
    { id: 'diarreia', text: 'Sofre de diarreia frequente?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['digestive'] },
    { id: 'gases_inchaco', text: 'Tem gases / inchaço abdominal frequente?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['digestive'] },
    { id: 'colonoscopia_endoscopia', text: 'Já fez colonoscopia ou endoscopia? Resultado?', type: 'text', required: false, tags: ['digestive'] },
    { id: 'frequencia_evacuacao', text: 'Frequência de evacuação (vezes por dia ou semana):', type: 'text', required: false, tags: ['digestive'] },
    { id: 'bristol_fezes', text: 'Consistência habitual das fezes (escala Bristol 1-7; 1-2 ressecado, 3-4 ideal, 5-7 solto):', type: 'number', required: false, tags: ['digestive'] },

    // ─── 11. SAÚDE HORMONAL (mulheres / homens) ───────────────────────────
    { id: 'ciclo_menstrual_regular', text: 'Ciclo menstrual regular? (para mulheres)', type: 'single', options: ['Sim', 'Não', 'Não se aplica'], required: false, tags: ['hormonal'] },
    { id: 'duracao_ciclo', text: 'Duração do ciclo (dias):', type: 'number', required: false, tags: ['hormonal'] },
    { id: 'anticoncepcional', text: 'Usa anticoncepcional hormonal? Qual?', type: 'text', required: false, tags: ['hormonal'] },
    { id: 'gestante_amamentando', text: 'Está gestante ou amamentando?', type: 'single', options: ['Sim', 'Não', 'Não se aplica'], required: false, tags: ['hormonal'] },
    { id: 'menopausa', text: 'Está na menopausa ou perimenopausa?', type: 'single', options: ['Sim', 'Não', 'Não se aplica'], required: false, tags: ['hormonal'] },
    { id: 'reposicao_hormonal', text: 'Faz reposição hormonal?', type: 'single', options: ['Sim', 'Não', 'Não se aplica'], required: false, tags: ['hormonal'] },
    { id: 'sintomas_baixa_testosterona', text: 'Tem sintomas de baixa testosterona (fadiga, libido reduzida, ganho de gordura)? (para homens)', type: 'single', options: ['Sim', 'Não', 'Não se aplica'], required: false, tags: ['hormonal'] },
    { id: 'trt_esteroides', text: 'Faz TRT ou usa/usou esteroides anabolizantes?', type: 'single', options: ['Sim', 'Não', 'Não se aplica'], required: false, tags: ['hormonal'] },

    // ─── 12. ROTINA E ESTILO DE VIDA ──────────────────────────────────────
    { id: 'horario_acordar', text: 'Horário que acorda:', type: 'text', required: false, tags: ['lifestyle'] },
    { id: 'horario_dormir', text: 'Horário que vai dormir:', type: 'text', required: false, tags: ['lifestyle'] },
    { id: 'turno_trabalho', text: 'Turno de trabalho (manhã, tarde, noite):', type: 'text', required: false, tags: ['lifestyle'] },
    { id: 'trabalho_presencial_remoto', text: 'Trabalha presencialmente ou remoto?', type: 'single', options: ['Presencial', 'Remoto', 'Híbrido'], required: false, tags: ['lifestyle'] },
    { id: 'rotina_tipica', text: 'Descreva brevemente sua rotina em um dia típico:', type: 'text', required: false, tags: ['lifestyle'] },
    { id: 'trabalho_esforco_fisico', text: 'Trabalho exige esforço físico intenso?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['lifestyle'] },
    { id: 'mais_6h_sentado', text: 'Passa mais de 6h sentado por dia?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['lifestyle'] },
    { id: 'tempo_lazer', text: 'Tem tempo livre para lazer / hobbies?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['lifestyle'] },
    { id: 'dificuldades_habitos', text: 'Quais são suas principais dificuldades para manter hábitos saudáveis?', type: 'text', required: false, tags: ['lifestyle'] },

    // ─── 13. OUTRAS INFORMAÇÕES ───────────────────────────────────────────
    { id: 'fumante', text: 'É fumante ou ex-fumante?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['other'] },
    { id: 'drogas_recreativas', text: 'Usa ou usou drogas recreativas?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['other'] },
    { id: 'tatuagens_extensas', text: 'Tem tatuagens extensas (pode interferir em bioimpedância)?', type: 'single', options: ['Sim', 'Não'], required: false, tags: ['other'] },
    { id: 'renda_alimentacao', text: 'Renda / custo máximo mensal para alimentação (opcional):', type: 'text', required: false, tags: ['other'] },
    { id: 'outras_informacoes', text: 'Há algo mais que considera importante o profissional saber sobre você?', type: 'text', required: false, tags: ['other'] },
  ],
  conditionalLogic: [
    { ifQuestion: 'objetivo_principal', ifValue: ['Outro'], thenShow: ['objetivo_outro'] },
  ],
  tags: [
    'identificacao',
    'anthropometry',
    'goal',
    'health',
    'medications',
    'diet',
    'food_emotional',
    'activity',
    'sleep',
    'stress',
    'digestive',
    'hormonal',
    'lifestyle',
    'other',
  ],
} as const;
